### ISSUE TITLE
Trains not issuing "Stop" command after coupling

### ISSUE THREAD

**Issue by Fevix** [wexp/RR-YardAiExtended#2]
A "recent" change in Railroader has trains in Yard mode stop after a Coupling operation. After installing this mod, that functionality is lost.

**Comment by wexp** [comment]
Development on this mod stopped with Railroader 2024.3, for the time being it's deprecated.
I recommend https://github.com/peterellisjones/Railroader-SmartOrders as an excellent upgrade for 2024.4+
