### ISSUE TITLE
Mod is intermittently working in game

### ISSUE THREAD

**Issue by Hogger109** [wexp/RR-YardAiExtended#3]
I've tried uninstalling and reinstalling the mod 3 times, and every time I load the game, the default AI yard car counts still appear, despite Railloader showing the mod to be "Enabled and loaded"

**Comment by wexp** [comment]
Development on this mod stopped with Railroader 2024.3, for the time being it's deprecated.
I recommend https://github.com/peterellisjones/Railroader-SmartOrders as an excellent upgrade for 2024.4+

**Comment by Hogger109** [comment]
That’s good to know. I really appreciated your mod while it lasted, thanks for the recommendation!
